pipeline {
    agent {
        label "centos7-generic"
    }

    options {
        timestamps()
    }

    parameters {
        string(defaultValue: '0.2.0', name: 'ausfinVersion', description: 'Version of Ausfin')
    }

    stages {
        stage('run') {
            environment {
                CONFIG = credentials('ausfin-scrape-config')
            }
            steps {
                sh """
                curl https://chromedriver.storage.googleapis.com/2.38/chromedriver_linux64.zip -O
                unzip chromedriver_linux64.zip

                python3.6 -m venv env
                . env/bin/activate
                pip install --upgrade pip setuptools
                pip install --upgrade ausfin==${params.ausfinVersion}

                ls

                export PATH=${WORKSPACE}:\$PATH
                export PYTHONUNBUFFERED=True

                echo \$PATH

                ausfin net-worth -c ${CONFIG} -o balance-data.json
                """
            }
        }
    }

    post {
        always {
            cleanWs()
        }
    }
}
