pipeline {
    agent {
        label "centos7-generic"
    }

    stages {
        stage('run') {
            environment {
                CONFIG = credentials('ausfin-scrape-config')
            }
            steps {
                sh """
                python3.6 -m venv env
                . env/bin/activate
                pip install --upgrade pip setuptools
                pip install ausfin

                ausfin net-worth -c ${CONFIG}
                """
            }
        }
    }

    post {
        always {
            cleanWs()
        }
    }
}
